#!/bin/sh
mkdir -p /ql/java
yum -y install unzip
unzip /root/jboss-eap-7.2.0.zip -d /ql/
tar -xvzf /root/jdk-8u202-linux-x64.tar.gz -C /ql/java
rm -f /etc/alternatives/java
rm -f /bin/java
rm -f /ql/java/current-java
rm -f /opt/jboss

ln -s /ql/java/jdk* /ql/java/current-java
ln -s /ql/java/current-java/bin/java /etc/alternatives/java
ln -s /etc/alternatives/java /bin/java

ln -s /ql/jboss* /opt/jboss
cp -prv /ql/jboss-eap-7.2/domain/configuration /ql/jboss-eap-7.2/domain/configuration_bak
